service: api-ecoGuard

frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  api:
    handler: handler.api
    events:
      - http:
          path: /{proxy+}
          method: any

plugins:
  - serverless-offline
